# Generated by Django 2.0.5 on 2018-05-02 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artiste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, default='', max_length=3000)),
                ('record_label', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('poster', models.CharField(blank=True, default='', max_length=500)),
                ('description', models.TextField(blank=True, default='', max_length=3000)),
                ('location', models.CharField(blank=True, default='', max_length=300)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(blank=True, default='', max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('location', models.CharField(blank=True, default='', max_length=300)),
                ('events', models.ManyToManyField(related_name='attender', to='api.Event')),
            ],
        ),
        migrations.AddField(
            model_name='artiste',
            name='events',
            field=models.ManyToManyField(related_name='performer', to='api.Event'),
        ),
        migrations.AddField(
            model_name='artiste',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='api.User'),
        ),
    ]
